# General info
site_name: Blockchain
site_description: Introducción a Blockchain
site_author: Luis Cu (luiscu@galileo.edu)

# Repository
repo_name: cuprumbot/blockchain
repo_url: https://github.com/cuprumbot/blockchain-course

# Copyright
copyright: 'Luis Cu (luiscu@galileo.edu)'

# Theme Configuration
theme:
  name: material
  #custom_dir: assets

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - codehilite:
  - toc:
      permalink: true

extra_css:
  - stylesheets/custom.css

#extra_javascript:
#  - js/custom.js

nav:
  - Inicio: index.md
  - Semana 1 - Introducción:
    - 'Teoría' : 'lessons/lesson1.md'
    - Práctica:
      - 'Cálculo de un hash' : 'exercises/part1/hash.md'
      - 'Encontrando un nonce' : 'exercises/part1/nonce.md'
      - 'Causando una colisión' : 'exercises/part1/collision.md'
      - 'Instalación de billetera' : 'exercises/part1/wallet.md'
      - 'Uso de faucet' : 'exercises/part1/faucet.md'
  - Semana 2 - Conceptos clave:
    - 'Teoría' : 'lessons/lesson2.md'    
  - Semana 3 - Aplicaciones:
    - 'Teoría' : 'lessons/lesson3.md'
    - Práctica:
      - 'Realizando una transacción' : 'exercises/part2/transaction.md'
      - 'Explorando el blockchain' : 'exercises/part2/explorer.md'
      - 'Identificando transacciones' : 'exercises/part2/calls.md'
  - Semana 4 - Contratos inteligentes:
    - 'Teoría' : 'lessons/lesson4.md'
    - Práctica:
      - 'Instalación de herramientas' : 'exercises/part3/installing.md'
      - 'Desplegando contratos en Ganache' : 'exercises/part3/ganache.md'
      - 'Desplegando contratos en testnet' : 'exercises/part3/testnet.md'
      - 'Pruebas con Truffle' : 'exercises/part3/testing.md'
      - 'Transacciones con Truffle' : 'exercises/part3/truffle.md'
  - Semana 5 - Práctica:
    - Práctica:
      - 'Errores por falta de gas' : 'exercises/part4/gas.md'
      - 'Logs como almacenamiento barato' : 'exercises/part4/log.md'
      - 'Leer y escribir hacia contrato' : 'exercises/part4/interaction.md'
#      - 'Utilizando Webpack' : 'exercises/part4/webpack.md'
#      - 'Web3 para interactuar con contrato' : 'exercises/part4/web3.md'
